---
- name: "Set up WSL with all needed packages"
  hosts: localhost
  connection: local

  vars_files:
    - vars.yml

  tasks:

    - name: "Include SSH / GPG key tasks"
      include_tasks: tasks/ssh_gpg.yml
      when: generate_ssh_key or generate_gpg_key

    - name: "Install NVM / Node / AVN"
      include_tasks: tasks/nvm_node.yml
      when: install_nvm_node or install_avn

    # Let's not worry about Yarn for now, seeing it has moved to versions 2, 3 and even 4
    # - name: "Ensure yarn is installed"
    #   community.general.npm:
    #     name: yarn
    #     global: true

    - name: "Include RBENV and Ruby tasks"
      include_tasks: tasks/ruby.yml
      when: install_rbenv_ruby

    - name: Enable PHP PPA and install PHP
      include_tasks: tasks/php.yml
      when: install_php

    - name: Download and install Composer
      include_tasks: tasks/composer.yml
      when: install_composer and php_installation_check.rc == 0
